<def f='glibc_src_2.29/elf/dl-error-skeleton.c' l='68' type='receiver_fct'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='138' u='r' c='_dl_signal_cexception'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='140' u='r' c='_dl_signal_cexception'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='145' u='r' c='_dl_signal_cexception'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='158' u='r' c='_dl_signal_cerror'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='160' u='r' c='_dl_signal_cerror'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='165' u='r' c='_dl_signal_cerror'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='228' u='r' c='_dl_receive_error'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='232' u='w' c='_dl_receive_error'/>
<use f='glibc_src_2.29/elf/dl-error-skeleton.c' l='237' u='w' c='_dl_receive_error'/>
<doc f='glibc_src_2.29/elf/dl-error-skeleton.c' l='61'>/* This points to a function which is called when an continuable error is
   received.  Unlike the handling of `catch&apos; this function may return.
   The arguments will be the `errstring&apos; and `objname&apos;.

   Since this functionality is not used in normal programs (only in ld.so)
   we do not care about multi-threaded programs here.  We keep this as a
   global variable.  */</doc>
