<inh f='include/c++/7/bits/exception.h' l='60' c='std::exception'/>
<def f='include/c++/7/stdexcept' l='197' ll='227'/>
<use f='include/c++/7/stdexcept' l='212' c='_ZNSt13runtime_errorC1ERKS_'/>
<use f='include/c++/7/stdexcept' l='213' c='_ZNSt13runtime_erroraSERKS_'/>
<use f='include/c++/7/stdexcept' l='213' c='_ZNSt13runtime_erroraSERKS_'/>
<ovr f='include/c++/7/stdexcept' l='230' c='std::range_error'/>
<use f='include/c++/7/stdexcept' l='230'/>
<ovr f='include/c++/7/stdexcept' l='241' c='std::overflow_error'/>
<use f='include/c++/7/stdexcept' l='241'/>
<ovr f='include/c++/7/stdexcept' l='252' c='std::underflow_error'/>
<use f='include/c++/7/stdexcept' l='252'/>
<ovr f='include/c++/7/system_error' l='341' c='std::system_error'/>
<use f='include/c++/7/system_error' l='341'/>
<use f='include/c++/7/system_error' l='348' c='_ZNSt12system_errorC1ESt10error_code'/>
<use f='include/c++/7/system_error' l='351' c='_ZNSt12system_errorC1ESt10error_codeRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='include/c++/7/system_error' l='354' c='_ZNSt12system_errorC1ESt10error_codePKc'/>
<use f='include/c++/7/system_error' l='360' c='_ZNSt12system_errorC1EiRKNSt3_V214error_categoryE'/>
<use f='include/c++/7/system_error' l='364' c='_ZNSt12system_errorC1EiRKNSt3_V214error_categoryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>16</size>
<doc f='include/c++/7/stdexcept' l='192'>/** Runtime errors represent problems outside the scope of a program;
   *  they cannot be easily predicted and can generally only be caught as
   *  the program executes.
   *  @brief One of two subclasses of exception.
   */</doc>
<mbr r='std::runtime_error::_M_msg' o='64' t='std::__cow_string'/>
<fun r='_ZNSt13runtime_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZNSt13runtime_errorC1EPKc'/>
<fun r='_ZNSt13runtime_errorC1ERKS_'/>
<fun r='_ZNSt13runtime_erroraSERKS_'/>
<fun r='_ZNSt13runtime_errorD1Ev'/>
<fun r='_ZNKSt13runtime_error4whatEv'/>
